In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
full = pd.read_csv('full_features.csv')
full.head()

,timestamp,load,weathertime,temperature,dewpoint,humidity,pressure,wind_dir,wind_speed,precip,...,uv_index,dow,doy,day,month,hour,minute,t_m24,t_m48,tdif
0,2012-10-27 00:05:00,700.7,2012-10-27 00:08:00,11.2,9.9,92,1018.8,SW,4.8,0.0,...,0.0,5,301,27,10,0,5,700.7,700.7,0.0
1,2012-10-27 00:10:00,694.7,2012-10-27 00:08:00,11.2,9.9,92,1018.8,SW,4.8,0.0,...,0.0,5,301,27,10,0,10,694.7,694.7,0.0
2,2012-10-27 00:15:00,692.8,2012-10-27 00:14:00,11.3,9.9,91,1018.8,SW,6.4,0.0,...,0.0,5,301,27,10,0,15,692.8,692.8,0.0
3,2012-10-27 00:20:00,686.5,2012-10-27 00:25:00,11.2,9.9,92,1018.8,SW,3.2,0.0,...,0.0,5,301,27,10,0,20,686.5,686.5,0.0
4,2012-10-27 00:25:00,685.3,2012-10-27 00:25:00,11.2,9.9,92,1018.8,SW,3.2,0.0,...,0.0,5,301,27,10,0,25,685.3,685.3,0.0